In [11]:
import numpy as np

In [ ]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [ ]:
# Q1 :-

NO, there is  no difference in the data type of variables list_ and array_list:

In [9]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# Q2 :-

In [23]:
print(array_list.dtype)
print(list(map(lambda x: type(x), list_)))

<U1
[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [ ]:
# Q3 :-

In [25]:
array_list = np.array(object = list_, dtype = int)

print(array_list.dtype)
print(list(map(lambda x: type(x), list_)))

int64
[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


Yes, there will  be difference in the data type of the elements present in the variables, list_ and
arra_list.

In [ ]:
# Q4 :-

In [26]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [29]:
print(np.shape(num_array))
print(np.size(num_array))

(2, 3)
6


In [ ]:
# Q5 :-

In [33]:
zero_array = np.zeros((3,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Q6 :-

In [35]:
identity_mat = np.eye(5,5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
